#!/usr/bin/env bash
# This script is displaying "Best School" 10 times, "bad luck" and "good luck" at the 4th and 8th interation respectively

Var='Best School'
i=1
while [ "$i" -le 10 ]
do
    if [ "$i" -eq 4 ]
    then
        echo "bad luck"
    elif [ "$i" -eq 8 ]
    then
        echo "good luck"
    else
        echo "$Var"
    fi
    ((i++))
done