#!/usr/bin/env bash
# Create SSH client configuration file
cat <<EOF > ~/.ssh/config
Host *
  HostName 100.27.11.16
  User ubuntu
  IdentityFile ~/.ssh/school
  IdentitiesOnly yes
  PasswordAuthentication no
EOF
